apiVersion: v1
kind: Namespace
metadata:
  name: ssamd
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ssamd
  namespace: ssamd
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ssamd
  template:
    metadata:
      labels:
        app: ssamd
    spec:
      containers:
        - name: ssamd
          image: kube-manifest.kr.ncr.ntruss.com/ssamd:a7016a2
          imagePullPolicy: Always
          # TODO : health check 추가 예정
          # livenessProbe:
          #   httpGet:
          #     path: /health
          #     port: 3200
          #   initialDelaySeconds: 5
          #   periodSeconds: 10
          # readinessProbe:
          #   tcpSocket:
          #     port: 3200
          #   initialDelaySeconds: 10
          #   timeoutSeconds: 5
          # startupProbe:
          #   httpGet:
          #     path: /health
          #     port: 3200
          #   failureThreshold: 5
          #   periodSeconds: 10
          # resources:
          #   limits:
          #     cpu: 500m
          #     memory: 2Gi
          #   requests:
          #     cpu: 200m
          #     memory: 1Gi
          command:
            - /bin/sh
          args:
            - "-ec"
            - yarn start
          ports:
            - containerPort: 3000
          # envFrom:
          #   - secretRef:
          #       name: api-server-dev
      imagePullSecrets:
        - name: docker-registry-login
---
apiVersion: v1
kind: Service
metadata:
  name: ssamd
  namespace: ssamd
spec:
  type: NodePort
  ports:
    - port: 3000
      targetPort: 3000
      nodePort: 30000
  selector:
    app: ssamd
