apiVersion: v1
kind: Namespace
metadata:
  name: ssamd
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ssamd
  namespace: ssamd
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ssamd
  template:
    metadata:
      labels:
        app: ssamd
    spec:
      containers:
        - name: ssamd
          image: kube-manifest.kr.ncr.ntruss.com/ssamd:61e2de2b
          command:
            - /bin/sh
            - -ec
          args:
            - |
              pnpm prisma migrate deploy
              pnpm start
          envFrom:
            - configMapRef:
                name: ssamd-server-env
          ports:
            - containerPort: 3000
      imagePullSecrets:
        - name: docker-registry-login
---
apiVersion: v1
kind: Service
metadata:
  namespace: ssamd
  name: ssamd
  labels:
    app: ssamd
spec:
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
  selector:
    app: ssamd
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  namespace: ssamd
  name: ssamd-ingress
  annotations:
    kubernetes.io/ingress.class: traefik
    cert-manager.io/issuer: tls-issuer
spec:
  rules:
    - host: "keylink.kr"
      http:
        paths:
          - path: "/api"
            pathType: Prefix
            backend:
              service:
                name: ssamd
                port:
                  number: 3000
  tls:
    - hosts:
        - "keylink.kr"
      secretName: tls-secret-ingress
