apiVersion: v1
kind: Namespace
metadata:
  name: ssamd-dev
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ssamd-dev
  namespace: ssamd-dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ssamd-dev
  template:
    metadata:
      labels:
        app: ssamd-dev
    spec:
      containers:
        - name: ssamd-dev
          image: kube-manifest.kr.ncr.ntruss.com/ssamd-dev:c22fbbf7
          env:
            - name: DATABASE_URL
              valueFrom:
                configMapKeyRef:
                  name: ssamd-dev-server-env
                  key: DATABASE_URL
          command:
            - /bin/sh
            - -ec
          args:
            - |
              pnpm -- npx prisma db push
              pnpm prisma generate
              pnpm start:dev
          ports:
            - containerPort: 3000
      imagePullSecrets:
        - name: docker-registry-login
---
apiVersion: v1
kind: Service
metadata:
  name: ssamd-dev
  namespace: ssamd-dev
spec:
  type: NodePort
  ports:
    - port: 3000
      targetPort: 3000
      nodePort: 30000
  selector:
    app: ssamd-dev
