apiVersion: v1
kind: Namespace
metadata:
  name: ssamd
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ssamd
  namespace: ssamd
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ssamd
  template:
    metadata:
      labels:
        app: ssamd
    spec:
      containers:
        - name: ssamd
          image: kube-manifest.kr.ncr.ntruss.com/ssamd:0894f6a1
          env:
            - name: DATABASE_URL
              valueFrom:
                configMapKeyRef:
                  name: ssamd-server-env
                  key: DATABASE_URL
          command:
            - /bin/sh
          args:
            - "-ec"
            - pnpm -- npx prisma db push
            - pnpm prisma generate
            - pnpm start
          ports:
            - containerPort: 3000
      imagePullSecrets:
        - name: docker-registry-login
---
apiVersion: v1
kind: Service
metadata:
  name: ssamd
  namespace: ssamd
spec:
  type: NodePort
  ports:
    - port: 3000
      targetPort: 3000
      nodePort: 30000
  selector:
    app: ssamd
