apiVersion: v1
kind: Namespace
metadata:
  name: ssamd
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ssamd
  namespace: ssamd
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ssamd
  template:
    metadata:
      labels:
        app: ssamd
    spec:
      containers:
        - name: ssamd
          image: >-
            kube-manifest.kr.ncr.ntruss.com/ssamd:bdf1e66c
          # env:
          #   - name: GOOGLE_CLIENT_ID
          #     valueFrom:
          #       configMapKeyRef:
          #         name: ssamd
          #         key: GOOGLE_CLIENT_ID
          command:
            - /bin/sh
          args:
            - "-ec"
            - yarn start
          ports:
            - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: ssamd
  namespace: ssamd
spec:
  type: NodePort
  ports:
    - port: 3000
      targetPort: 3000
      nodePort: 30000
  selector:
    app: ssamd
